### ISSUE TITLE
考虑为非VIP用户爬取VIP专有课程视频？

### ISSUE THREAD

**Issue by PerssonBrown** [immccn123/Yangcong-tools#6]
经验证，该洋葱工具可以使非洋葱VIP用户完成VIP专有作业。

进一步的，是否可以考虑爬取VIP专有视频，实现~~共产主义~~？

**Comment by PerssonBrown** [comment]
本人没有购买洋葱VIP，但是在使用该工具后，却完成了VIP专有作业。（见下图）
<img width="587" alt="屏幕截图 2023-07-20 212602" src="https://github.com/immccn123/Yangcong-tools/assets/83103475/4b8f9506-5660-437d-80d8-a59215b507df">

**Comment by PerssonBrown** [comment]
洋葱对视频下载似乎有鉴权，该功能无法完成。

**Comment by yyds070422** [comment]
这是哪个工具

**Comment by immccn123** [comment]
> 这是哪个工具

@yyds070422 您希望表达什么？

如果有其他讨论的话请新开 issue 而不是在无关的 issue 里交流，避免搔扰其他人。

**Comment by yyds070422** [comment]
哦哦下栽上了  谢谢咯
